<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_550736b4eeebc',
	'title' => __(__('Company', 'couponhut'), 'couponhut'),
	'fields' => array (
		array (
			'key' => 'field_55073707dee91',
			'label' => __(__('Company Logo', 'couponhut'), 'couponhut'),
			'name' => 'company_logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_55225d80cd66e',
			'label' => __(__('Company Website', 'couponhut'), 'couponhut'),
			'name' => 'company_website',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'deal_company',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_55605fb7df4d0',
	'title' => __(__('Contact', 'couponhut'), 'couponhut'),
	'fields' => array (
		array (
			'key' => 'field_5563003417fa3',
			'label' => __(__('Image Title', 'couponhut'), 'couponhut'),
			'name' => 'image_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55ed438821018',
			'label' => __(__('Image or Map Location', 'couponhut'), 'couponhut'),
			'name' => 'image_or_map_location',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'image' => 'Image',
				'map' => 'Map Location',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'map',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_556063551154d',
			'label' => __(__('Upload Image', 'couponhut'), 'couponhut'),
			'name' => 'upload_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55ed438821018',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_556060065ab2d',
			'label' => __(__('Image Text', 'couponhut'), 'couponhut'),
			'name' => 'image_text',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55ed438821018',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_55ed434b21017',
			'label' => __(__('Location', 'couponhut'), 'couponhut'),
			'name' => 'location',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55ed438821018',
						'operator' => '==',
						'value' => 'map',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-contact.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_553527fa98297',
	'title' => __(__('Deal Category', 'couponhut'), 'couponhut'),
	'fields' => array (
		array (
			'key' => 'field_55352808d52c4',
			'label' => __(__('Icon', 'couponhut'), 'couponhut'),
			'name' => 'icon',
			'type' => 'fonticonpicker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_null' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'deal_category',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_55c4d6b94af2d',
	'title' => __(__('Show Top Search Header', 'couponhut'), 'couponhut'),
	'fields' => array (
		array (
			'key' => 'field_55c4d6c6cc1e5',
			'label' => __(__('Search Header', 'couponhut'), 'couponhut'),
			'name' => 'search_header',
			'type' => 'radio',
			'instructions' => __(__('Display search block at the top of the page.', 'couponhut'), 'couponhut'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'template-submit-deal.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_55016dc725a05',
	'title' => __(__('Single Deal', 'couponhut'), 'couponhut'),
	'fields' => array (
		array (
			'key' => 'field_5519756e0f4e2',
			'label' => __(__('Deal Type', 'couponhut'), 'couponhut'),
			'name' => 'deal_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'discount' => 'Discount',
				'coupon' => 'Coupon',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'discount',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_5683c0ebd307f',
			'label' => __(__('Printable Coupon', 'couponhut'), 'couponhut'),
			'name' => 'printable_coupon',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5519756e0f4e2',
						'operator' => '==',
						'value' => 'coupon',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5683c22bbfa74',
			'label' => __(__('Print Image', 'couponhut'), 'couponhut'),
			'name' => 'print_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5683c0ebd307f',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_554f8e55b6dd8',
			'label' => __(__('Deal Summary', 'couponhut'), 'couponhut'),
			'name' => 'deal_summary',
			'type' => 'textarea',
			'instructions' => __(__('The text that appears on the side in the single deal page.', 'couponhut'), 'couponhut'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_551976ac0f4e5',
			'label' => __(__('Redirect to offer URL', 'couponhut'), 'couponhut'),
			'name' => 'redirect_to_offer',
			'type' => 'checkbox',
			'instructions' => __(__('If it\'s enabled, the user will be redirected to the web site of the offer code.', 'couponhut'), 'couponhut'),
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5519756e0f4e2',
						'operator' => '==',
						'value' => 'coupon',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'enable' => 'Enable',
			),
			'default_value' => array (
				'enable' => 'enable',
			),
			'layout' => 'vertical',
			'toggle' => 0,
		),
		array (
			'key' => 'field_55532006b5e0c',
			'label' => __(__('Image Type', 'couponhut'), 'couponhut'),
			'name' => 'image_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'image' => 'Image',
				'slider' => 'Slider',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'image',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_55016dd111b9f',
			'label' => __(__('Image', 'couponhut'), 'couponhut'),
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55532006b5e0c',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56b75ea64f4f7',
			'label' => __(__('Header Image', 'couponhut'), 'couponhut'),
			'name' => 'header_image',
			'type' => 'image',
			'instructions' => __(__('Upload image if you want the single deal page to have its own header different from the thumbnail..', 'couponhut'), 'couponhut'),
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55532006b5e0c',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5553204db5e0d',
			'label' => __(__('Slider', 'couponhut'), 'couponhut'),
			'name' => 'slider',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55532006b5e0c',
						'operator' => '==',
						'value' => 'slider',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_5553205db5e0e',
					'label' => __(__('Image', 'couponhut'), 'couponhut'),
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_55532006b5e0c',
								'operator' => '==',
								'value' => 'slider',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
			'collapsed' => '',
		),
		array (
			'key' => 'field_551976780f4e4',
			'label' => __(__('Coupon Code', 'couponhut'), 'couponhut'),
			'name' => 'coupon_code',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5519756e0f4e2',
						'operator' => '==',
						'value' => 'coupon',
					),
					array (
						'field' => 'field_5683c0ebd307f',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55016e0911ba1',
			'label' => __(__('Discount Value', 'couponhut'), 'couponhut'),
			'name' => 'discount_value',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55016e3011ba3',
			'label' => __(__('URL', 'couponhut'), 'couponhut'),
			'name' => 'url',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55016e3d11ba4',
			'label' => __(__('Expiring Date', 'couponhut'), 'couponhut'),
			'name' => 'expiring_date',
			'type' => 'date_picker',
			'instructions' => __(__('The deal will expire exactly when the selected day begins.', 'couponhut'), 'couponhut'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'Y/m/d',
			'first_day' => 1,
		),
		array (
			'key' => 'field_568a54a25476a',
			'label' => __(__('Show Pricing Fields', 'couponhut'), 'couponhut'),
			'name' => 'show_pricing_fields',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show',
			'default_value' => 0,
		),
		array (
			'key' => 'field_568a548054767',
			'label' => __(__('Old Price', 'couponhut'), 'couponhut'),
			'name' => 'old_price',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_568a54a25476a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_568a548f54768',
			'label' => __(__('New Price', 'couponhut'), 'couponhut'),
			'name' => 'new_price',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_568a54a25476a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_568a549854769',
			'label' => __(__('Save', 'couponhut'), 'couponhut'),
			'name' => 'save',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_568a54a25476a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5673f4f869107',
			'label' => __(__('Registered Members Only', 'couponhut'), 'couponhut'),
			'name' => 'registered_members_only',
			'type' => 'true_false',
			'instructions' => __(__('Important! Enable Ultimate Member plugin if this is set.', 'couponhut'), 'couponhut'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable',
			'default_value' => 0,
		),
		array (
			'key' => 'field_55d30607a99a0',
			'label' => __(__('Show Location', 'couponhut'), 'couponhut'),
			'name' => 'show_location',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'show',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_55acf7df457a3',
			'label' => __(__('Location', 'couponhut'), 'couponhut'),
			'name' => 'location',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55d30607a99a0',
						'operator' => '==',
						'value' => 'show',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '',
		),
		array (
			'key' => 'field_5645d20916d2e',
			'label' => __(__('Map Zoom', 'couponhut'), 'couponhut'),
			'name' => 'map_zoom',
			'type' => 'number',
			'instructions' => __(__('Enter map zoom level from 1 to 20.', 'couponhut'), 'couponhut'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 16,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => 20,
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'deal',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;